apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default
  source:
    chart: example-chart
    repoURL: https://github.com/KostyantynG/k8s_argocd.git
    targetRevision: HEAD
    path: temp/example-chart
    helm:
      releaseName: myapp-argo-application
  destination:
    server: https://kubernetes.default.svc
    namespace: appns

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true