apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kostyantyng.github.io/k8s_argocd/charts
    targetRevision: 0.1.0
    chart: example-chart
  destination:
    server: https://kubernetes.default.svc